select * from dbt_actuaries.ext_all_claims_combined_20210131
union all 
select 
date_knowledge,
tpa_report_date,
tbl_source,
policy_id,
claims_policy_number,
carrier,
claim_number,
major_peril,
peril,
cat_code,
claim_status,
date_of_loss,
date_first_notice_of_loss,
cast(date_closed as date) as date_closed,
reinsurance_treaty,
is_cat,
is_ebsl,
loss_paid,
loss_net_reserve,
loss_incurred,
expense_paid,
expense_net_reserve,
expense_incurred,
total_paid,
total_net_reserve,
total_incurred,
recoveries,
recoverable_depreciation,
accident_year,
accident_month,
maturity,
policy_number,
date_effective,
date_expires,
attribution_channel,
organization_id,
organization_name,
attributed_root_organization_id,
root_org_name,
product,
cast(property_data_address_zip as string) as property_data_address_zip,
property_data_address_city,
property_data_address_county,
property_data_address_state,
coverage_a,
coverage_b,
coverage_c,
coverage_d,
cast(property_data_square_footage as string) as property_data_square_footage,
property_data_construction_type,
cast(calculated_fields_age_of_home as string) as calculated_fields_age_of_home,
cast(calculated_fields_age_of_roof as string) as calculated_fields_age_of_roof,
latest_policy_update_id,
is_outside_policy_lifecyle,
claim_closed_no_total_payment,
claim_closed_no_loss_payment,
claim_count,
peril_group,
non_cat_capped_loss_development_factor,
cat_loss_development_factor,
development_factor,
is_cat_override,
cat_event_id
from dbt_actuaries.salesforce_issue_claims_20210131